/** ***************************************************************************************
 * Autora: Esther de Santana Araújo e Ariana de Jesus Santos Pereira
 * Componente Curricular: MI-Programação
 * Concluido em: 08/02/2019
 * Declaro que este código foi elaborado por nós de forma individual e não contém nenhum
 * trecho de código de outro colega ou de outro autor, tais como provindos de livros e
 * apostilas, e páginas ou documentos eletrônicos da Internet. Qualquer trecho de código
 * de outra autoria que não a minha está destacado com uma citação para o autor e a fonte
 * do código, e estou ciente que estes trechos não serão considerados para fins de avaliação.
 ***************************************************************************************** */
package view;

import java.util.List;
import roteirização.Controller;
import util.Vertice;

/**
 *
 * @author Esther Araújo e Ariana Pereira
 */
public class FinalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FinalJFrame
     */
    private Controller controller;
    
    public FinalJFrame(Controller controller) {
        initComponents();
        this.controller = controller;
        
        theJPanel1.setListaCidades(controller);
        this.setVisible(true);
        this.setResizable(false);
        
    }
    
    public void colorRota(List<Vertice> rota) {
        theJPanel1.setColorRota(rota);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theJPanel1 = new view.TheJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getContentPane().add(theJPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.TheJPanel theJPanel1;
    // End of variables declaration//GEN-END:variables
}
