/** ***************************************************************************************
 * Autora: Esther de Santana Araújo e Ariana de Jesus Santos Pereira
 * Componente Curricular: MI-Programação
 * Concluido em: 08/02/2019
 * Declaro que este código foi elaborado por nós de forma individual e não contém nenhum
 * trecho de código de outro colega ou de outro autor, tais como provindos de livros e
 * apostilas, e páginas ou documentos eletrônicos da Internet. Qualquer trecho de código
 * de outra autoria que não a minha está destacado com uma citação para o autor e a fonte
 * do código, e estou ciente que estes trechos não serão considerados para fins de avaliação.
 ***************************************************************************************** */
package view;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import roteirização.Controller;
import util.Vertice;

/**
 *
 * @author Esther Araújo e Ariana Pereira
 */
public class TheJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TheJPanel
     */
    public TheJPanel() {
        initComponents();
    }

    public void setListaCidades (Controller controller) {
        listaCidadesJPanel1.addCheckBox(controller.getVerticeFromGrafo());
        listaCidadesJPanel1.setController(controller);
        mapaJPanel2.getVertice(controller);
        infoJPanel1.grupoBotoes(controller.getCarros(), controller);
        botoesJPanel1.ativarBotoes(controller);
    }
    
    public void setColorRota(List<Vertice> rota) {
        mapaJPanel2.getRota(rota);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        listaCidadesJPanel1 = new view.ListaCidadesJPanel();
        jPanel2 = new javax.swing.JPanel();
        botoesJPanel1 = new view.BotoesJPanel();
        infoJPanel1 = new view.InfoJPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mapaJPanel2 = new view.MapaJPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(listaCidadesJPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(botoesJPanel1, gridBagConstraints);
        jPanel2.add(infoJPanel1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout mapaJPanel2Layout = new javax.swing.GroupLayout(mapaJPanel2);
        mapaJPanel2.setLayout(mapaJPanel2Layout);
        mapaJPanel2Layout.setHorizontalGroup(
            mapaJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        mapaJPanel2Layout.setVerticalGroup(
            mapaJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mapaJPanel2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.BotoesJPanel botoesJPanel1;
    private view.InfoJPanel infoJPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private view.ListaCidadesJPanel listaCidadesJPanel1;
    private view.MapaJPanel mapaJPanel2;
    // End of variables declaration//GEN-END:variables
}
